server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3006/productdb
    username : root 
    password : Root@123456
    driver-class-name: com.mysql.jdbc.driver
   
  jpa: 
    hibernate:
      ddl-auto: update
      
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
     
      
   
 