server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
     
        routes:
        - id: EMPLOYEE-SERVICE
          uri:
            lb://EMPLOYEE-SERVICE
          predicates:
          - Path=/EMPLOYEE/**
          
        - id: EMPLOYEE-SERVICE
          uri:
            lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/DEPARTMENT/**
          
          
     
     
           
    
      